(async function(){
  var user='ALE'; var sent=0,erros=0;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "22/12/2023", 39657.16, "Aplicação inicial"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "04/01/2024", 41128.42, "Atualização de saldo"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "31/01/2024", 41483.16, "Atualização de saldo"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "13/02/2024", 41627.94, "Atualização de saldo"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "30/03/2024", 42206.05, "Atualização de saldo"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "30/04/2024", 96039.9, "Atualização de saldo"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "09/06/2024", 96627.92, "2"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "16/06/2024", 96827.81, "2"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "04/08/2024", 98169.8, "2"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "30/08/2024", 98942.9, "2"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "05/10/2024", 99957.89, "2"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "10/11/2024", 100954.67, "2"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "30/11/2024", 101128.54, "2"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "08/12/2024", 101552.04, "2"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "11/01/2025", 101945.91, "2"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "06/03/2025", 103747.56, "2"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "30/03/2025", 104638.95, "2"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "06/07/2025", 107451.16, "2"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "31/08/2025", 109858.13, "2"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "05/10/2025", 111363.63, "2"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "26/10/2025", 111618.9, "2"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "30/11/2025", 112601.42, "2"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "04/01/2026", 114046.84, "2"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "01/02/2026", 115364.79, "2"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "01/03/2026", 116441.55, "2"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "30/03/2026", 117692.86, "2"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA DI MASTER", "20/04/2026", 118578.09, "Atualização de saldo"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('✓ SAFRA DI MASTER (27 logs)');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "22/12/2023", 29114, "Aplicação inicial"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "04/01/2024", 30083.66, "1"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "31/01/2024", 30348.68, "1"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "13/02/2024", 30461.29, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "30/03/2024", 30917.08, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "30/04/2024", 56422.27, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "09/06/2024", 56562.94, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "16/06/2024", 56872.95, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "04/08/2024", 57660.4, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "30/08/2024", 58124.88, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "05/10/2024", 58753.7, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "10/11/2024", 59330.85, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "30/11/2024", 59432.32, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "08/12/2024", 59685.54, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "11/01/2025", 59931.91, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "06/03/2025", 61070.72, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "30/03/2025", 61615.92, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "06/07/2025", 63334.85, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "31/08/2025", 64775.36, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "05/10/2025", 65664.97, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "26/10/2025", 66212.83, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "30/11/2025", 66399.76, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "04/01/2026", 67250.94, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "01/02/2026", 68048.59, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "01/03/2026", 68715.78, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "30/03/2026", 69385.59, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "02/04/2026", 70179.72, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "SAFRA VITESSE", "20/04/2026", 69869.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  console.log('✓ SAFRA VITESSE (28 logs)');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM CRAPRE - PRE IE", "16/06/2024", 24145.63, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM CRAPRE - PRE IE", "04/08/2024", 24422.98, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM CRAPRE - PRE IE", "30/08/2024", 24475.9, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM CRAPRE - PRE IE", "05/10/2024", 24851.44, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM CRAPRE - PRE IE", "10/11/2024", 25058.26, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM CRAPRE - PRE IE", "30/11/2024", 24038.71, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM CRAPRE - PRE IE", "08/12/2024", 24146.46, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM CRAPRE - PRE IE", "11/01/2025", 25683.88, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM CRAPRE - PRE IE", "06/03/2025", 20745.44, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM CRAPRE - PRE IE", "30/03/2025", 21062.49, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM CRAPRE - PRE IE", "06/07/2025", 21835.76, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM CRAPRE - PRE IE", "31/08/2025", 20657.09, "cra pagou 1344,19"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM CRAPRE - PRE IE", "05/10/2025", 22606.59, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM CRAPRE - PRE IE", "26/10/2025", 23394.99, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM CRAPRE - PRE IE", "30/11/2025", 22219.98, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM CRAPRE - PRE IE", "04/01/2026", 22635.8, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM CRAPRE - PRE IE", "01/02/2026", 23160.22, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM CRAPRE - PRE IE", "01/03/2026", 23192.17, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM CRAPRE - PRE IE", "30/03/2026", 23678.57, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM CRAPRE - PRE IE", "20/04/2026", 23966.33, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM CRAPRE - PRE IE", "02/04/2026", 24662.65, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM CRAPRE - PRE IE", "20/04/2026", 24816.33, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM CRAPRE - PRE IE", "02/05/2026", 24888.38, ""]});
  if(r&&r.ok)sent++; else erros++;
  console.log('✓ TCM CRAPRE - PRE IE (23 logs)');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "26/07/2022", 5000.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "25/08/2022", 5117.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "29/09/2022", 5113.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "27/10/2022", 5056.5, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "02/02/2023", 4924.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "03/03/2023", 4936.5, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "30/03/2023", 4882.5, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "01/05/2023", 4849.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "31/05/2023", 4762.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "06/07/2023", 4895.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "31/07/2023", 4945.5, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "31/08/2023", 4981.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "28/09/2023", 4960.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "25/10/2023", 5075.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "30/11/2023", 5159.5, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "04/01/2024", 5168.5, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "31/01/2024", 5183.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "13/02/2024", 5184.5, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "30/03/2024", 5170.5, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "30/04/2024", 5250.5, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "09/06/2024", 5215.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "16/06/2024", 5199.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "04/08/2024", 5261.5, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "30/08/2024", 5287.5, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "05/10/2024", 5250.5, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "10/11/2024", 5165.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "30/11/2024", 5159.5, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "08/12/2024", 5164.5, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "11/01/2025", 5127.5, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "06/03/2025", 5075.5, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "30/03/2025", 5225.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "06/07/2025", 5247.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "31/08/2025", 5270.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "05/10/2025", 5207.5, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "26/10/2025", 5284.5, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "30/11/2025", 5308.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "04/01/2026", 5308.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "01/02/2026", 5291.5, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "01/03/2026", 5370.5, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "30/03/2026", 5285.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "20/04/2026", 5356.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "KNCR11", "02/05/2026", 5349.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  console.log('✓ KNCR11 (42 logs)');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "01/05/2023", 497.82, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "31/05/2023", 480.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "06/07/2023", 470.02, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "31/07/2023", 1441.08, "4,87 dolar"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "31/08/2023", 1521.06, "4,82 dolar"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "28/09/2023", 1533.77, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "25/10/2023", 1569.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "30/11/2023", 1497.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "04/01/2024", 1944.0, "COT 04/01/24"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "31/01/2024", 1999.62, "COT 26.1.24"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "13/02/2024", 2019.23, "COT 13/2/24"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "30/03/2024", 2066.55, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "30/04/2024", 2117.7, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "09/06/2024", 2180.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "16/06/2024", 2192.81, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "04/08/2024", 2282.5, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "30/08/2024", 2268.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "05/10/2024", 2268.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "10/11/2024", 2300.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "30/11/2024", 2300.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "08/12/2024", 2300.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "11/01/2025", 2300.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "06/03/2025", 2300.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "30/03/2025", 2323.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "06/07/2025", 2323.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "31/08/2025", 2323.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "05/10/2025", 2597.08, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "26/10/2025", 2597.08, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "30/11/2025", 2597.08, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "04/01/2026", 2597.08, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "01/02/2026", 2597.08, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "01/03/2026", 2597.08, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "30/03/2026", 2597.08, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "20/04/2026", 2597.08, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "02/05/2026", 1980.58, ""]});
  if(r&&r.ok)sent++; else erros++;
  console.log('✓ Avenue - Dólar (35 logs)');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "04/01/2024", 521.96, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "31/01/2024", 1016.06, "COT 26.1.24"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "13/02/2024", 1012.28, "COT 13/2/24"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "30/03/2024", 2003.9, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "30/04/2024", 3055.02, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "09/06/2024", 118.01, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "16/06/2024", 20.57, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "04/08/2024", 20.64, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "30/08/2024", 20.62, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "05/10/2024", 20.62, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "10/11/2024", 20.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "30/11/2024", 20.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "11/01/2025", 20.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "06/03/2025", 20.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "30/03/2025", 1520.21, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "06/07/2025", 15.41, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "31/08/2025", 15.41, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "05/10/2025", 15.41, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "26/10/2025", 15.41, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "30/11/2025", 15.41, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "04/01/2026", 15.41, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "01/02/2026", 15.6, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "01/03/2026", 15.6, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "30/03/2026", 15.6, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "20/04/2026", 15.6, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "02/05/2026", 15.6, ""]});
  if(r&&r.ok)sent++; else erros++;
  console.log('✓ Wise (26 logs)');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/06/2022", 41141.65, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/07/2022", 42985.62, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/08/2022", 48370.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/09/2022", 48370.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/10/2022", 42974.21, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/11/2022", 42986.4, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/01/2023", 41539.45, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "28/02/2023", 32124.24, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/03/2023", 32124.24, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/04/2023", 32988.73, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/05/2023", 32988.73, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/06/2023", 32988.73, "igual"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/07/2023", 32988.73, "IGUAL"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/08/2023", 32988.73, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/09/2023", 34400.3, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/10/2023", 34400.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/11/2023", 34400.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/12/2023", 41022.3, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/01/2024", 40468.65, "pelo app"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "29/02/2024", 42929.21, "pelo app"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/03/2024", 41018.88, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/04/2024", 37639.55, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/05/2024", 35505.86, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/06/2024", 35465.21, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/07/2024", 38094.04, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/08/2024", 40063.08, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/09/2024", 37891.17, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/10/2024", 35388.65, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/11/2024", 35427.61, "estimado"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/12/2024", 36207.16, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/01/2025", 36207.16, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "28/02/2025", 39325.25, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/03/2025", 41734.34, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/07/2025", 42820.52, "nao atual"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/08/2025", 39226.54, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/09/2025", 53591.94, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/10/2025", 58371.71, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/11/2025", 69310.51, "estimado"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/12/2025", 69457.23, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/01/2026", 77245.3, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "28/02/2026", 85088.46, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/03/2026", 82088.49, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/04/2026", 88760.11, ""]});
  if(r&&r.ok)sent++; else erros++;
  console.log('✓ FMP-FGTS Eletrobrás (43 logs)');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "09/06/2024", 4920.12, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "16/06/2024", 4664.83, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "04/08/2024", 4632.77, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "30/08/2024", 4625.05, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "05/10/2024", 4651.51, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "10/11/2024", 4678.01, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "30/11/2024", 6434.38, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "08/12/2024", 6061.78, "caixa radio"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "11/01/2025", 5266.62, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "06/03/2025", 5292.98, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "30/03/2025", 5220.13, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "06/07/2025", 5224.53, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "05/10/2025", 3226.98, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "26/10/2025", 3179.05, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "30/11/2025", 4342.47, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "04/01/2026", 3998.67, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "01/02/2026", 5924.15, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "01/03/2026", 7064.23, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "30/03/2026", 7104.15, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "20/04/2026", 7152.07, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "02/05/2026", 6443.72, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "20/04/2026", 6473.1, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "02/05/2026", 6486.46, ""]});
  if(r&&r.ok)sent++; else erros++;
  console.log('✓ Poupança Bororos (23 logs)');
  console.log('Total:',sent,'ok,',erros,'erros');
  alert('Concluído! '+sent+' logs gravados. Erros: '+erros);
})();