(async function(){
  var user='ALE'; var sent=0,erros=0;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "01/05/2023", 497.82, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "31/05/2023", 480.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "06/07/2023", 470.02, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "31/07/2023", 1441.08, "4,87 dolar"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "31/08/2023", 1521.06, "4,82 dolar"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "28/09/2023", 1533.77, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "25/10/2023", 1569.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "30/11/2023", 1497.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "04/01/2024", 1944.0, "COT 04/01/24"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "31/01/2024", 1999.62, "COT 26.1.24"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "13/02/2024", 2019.23, "COT 13/2/24"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "30/03/2024", 2066.55, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "30/04/2024", 2117.7, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "09/06/2024", 2180.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "16/06/2024", 2192.81, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "04/08/2024", 2282.5, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "30/08/2024", 2268.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "05/10/2024", 2268.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "10/11/2024", 2300.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "30/11/2024", 2300.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "08/12/2024", 2300.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "11/01/2025", 2300.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "06/03/2025", 2300.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "30/03/2025", 2323.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "06/07/2025", 2323.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "31/08/2025", 2323.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "05/10/2025", 2597.08, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "26/10/2025", 2597.08, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "30/11/2025", 2597.08, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "04/01/2026", 2597.08, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "01/02/2026", 2597.08, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "01/03/2026", 2597.08, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "30/03/2026", 2597.08, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "20/04/2026", 2597.08, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Avenue", "Avenue - Dólar", "02/05/2026", 1980.58, ""]});
  if(r&&r.ok)sent++; else erros++;
  console.log('✓ Avenue - Dólar (35 logs)');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "04/01/2024", 521.96, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "31/01/2024", 1016.06, "COT 26.1.24"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "13/02/2024", 1012.28, "COT 13/2/24"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "30/03/2024", 2003.9, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "30/04/2024", 3055.02, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "09/06/2024", 118.01, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "16/06/2024", 20.57, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "04/08/2024", 20.64, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "30/08/2024", 20.62, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "05/10/2024", 20.62, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "10/11/2024", 20.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "30/11/2024", 20.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "11/01/2025", 20.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "06/03/2025", 20.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "30/03/2025", 1520.21, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "06/07/2025", 15.41, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "31/08/2025", 15.41, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "05/10/2025", 15.41, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "26/10/2025", 15.41, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "30/11/2025", 15.41, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "04/01/2026", 15.41, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "01/02/2026", 15.6, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "01/03/2026", 15.6, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "30/03/2026", 15.6, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "20/04/2026", 15.6, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Wise", "Wise", "02/05/2026", 15.6, ""]});
  if(r&&r.ok)sent++; else erros++;
  console.log('✓ Wise (26 logs)');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/06/2022", 41141.65, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/07/2022", 42985.62, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/08/2022", 48370.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/09/2022", 48370.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/10/2022", 42974.21, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/11/2022", 42986.4, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/01/2023", 41539.45, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "28/02/2023", 32124.24, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/03/2023", 32124.24, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/04/2023", 32988.73, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/05/2023", 32988.73, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/06/2023", 32988.73, "igual"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/07/2023", 32988.73, "IGUAL"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/08/2023", 32988.73, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/09/2023", 34400.3, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/10/2023", 34400.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/11/2023", 34400.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/12/2023", 41022.3, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/01/2024", 40468.65, "pelo app"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "29/02/2024", 42929.21, "pelo app"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/03/2024", 41018.88, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/04/2024", 37639.55, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/05/2024", 35505.86, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/06/2024", 35465.21, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/07/2024", 38094.04, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/08/2024", 40063.08, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/09/2024", 37891.17, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/10/2024", 35388.65, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/11/2024", 35427.61, "estimado"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/12/2024", 36207.16, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/01/2025", 36207.16, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "28/02/2025", 39325.25, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/03/2025", 41734.34, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/07/2025", 42820.52, "nao atual"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/08/2025", 39226.54, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/09/2025", 53591.94, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/10/2025", 58371.71, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/11/2025", 69310.51, "estimado"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/12/2025", 69457.23, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/01/2026", 77245.3, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "28/02/2026", 85088.46, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "31/03/2026", 82088.49, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Caixa", "FMP-FGTS Eletrobrás", "30/04/2026", 88760.11, ""]});
  if(r&&r.ok)sent++; else erros++;
  console.log('✓ FMP-FGTS Eletrobrás (43 logs)');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "09/06/2024", 4920.12, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "16/06/2024", 4664.83, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "04/08/2024", 4632.77, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "30/08/2024", 4625.05, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "05/10/2024", 4651.51, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "10/11/2024", 4678.01, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "30/11/2024", 6434.38, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "08/12/2024", 6061.78, "caixa radio"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "11/01/2025", 5266.62, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "06/03/2025", 5292.98, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "30/03/2025", 5220.13, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "06/07/2025", 5224.53, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "05/10/2025", 3226.98, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "26/10/2025", 3179.05, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "30/11/2025", 4342.47, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "04/01/2026", 3998.67, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "01/02/2026", 5924.15, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "01/03/2026", 7064.23, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "30/03/2026", 7104.15, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "20/04/2026", 7152.07, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "02/05/2026", 6443.72, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "20/04/2026", 6473.1, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Itaú Bororos", "Poupança Bororos", "02/05/2026", 6486.46, ""]});
  if(r&&r.ok)sent++; else erros++;
  console.log('✓ Poupança Bororos (23 logs)');
  console.log('Total:',sent,'ok,',erros,'erros');
  alert('Concluído! '+sent+' logs. Erros: '+erros);
})();