(async function(){
  var user='ALE'; var sent=0,erros=0,txSent=0;
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "MM. MAN Absolute Vertex FIC FIM", "Multimercado", "", 20000.0, 21627.21, "", "", "", "", "", "", "", "", "Sim"]});
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "MM. MAN Ibiuna Hedge FIC FIM", "Multimercado", "", 50000.0, 53124.72, "", "", "", "", "", "", "", "", "Sim"]});
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "RF.LCA vence 17/05", "Renda Fixa", "", 10531.17, 10531.17, "", "", "", "", "", "", "", "", "Sim"]});
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "RF.LCA vence 05/06", "Renda Fixa", "", 34575.46, 34575.46, "", "", "", "", "", "", "", "", "Sim"]});
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "RF.LCA vence 03/07", "Renda Fixa", "", 7053.89, 7192.06, "", "", "", "", "", "", "", "", "Sim"]});
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "RF.LCA vence 21/08", "Renda Fixa", "", 18260.7, 18525.18, "", "", "", "", "", "", "", "", "Sim"]});
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "RF.LCA vence 5/09", "Renda Fixa", "", 75674.93, 77146.68, "", "", "", "", "", "", "", "", "Sim"]});
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "RF.LCA vence 4/12", "Renda Fixa", "", 32283.84, 33786.04, "", "", "", "", "", "", "", "", "Sim"]});
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "LCA Safra pre vence 30/11", "Renda Fixa", "", 15112.71, 15379.03, "", "", "", "", "", "", "", "", "Sim"]});
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "LCA vence 04/12/2023", "Renda Fixa", "", 50329.8, 51248.04, "", "", "", "", "", "", "", "", "Sim"]});
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "LCA Safra pre vence 18/12", "Renda Fixa", "", 65000.0, 66656.51, "", "", "", "", "", "", "", "", "Sim"]});
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "TCM LCAPR PRE 11.85% v.5/9", "Renda Fixa", "", 29298.58, 29639.07, "", "", "", "", "", "", "", "", "Sim"]});
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "TCM LCAPR PRE 11.75% v.9/10", "Renda Fixa", "", 9808.36, 10022.55, "", "", "", "", "", "", "", "", "Sim"]});
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "RF. LCA Emissao Safra Pre", "Renda Fixa", "", 24889.81, 60084.12, "", "", "", "", "", "", "", "", "Sim"]});
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "RF. CDB emissao terceiros IPCA", "Renda Fixa", "", 4501.35, 4501.35, "", "", "", "", "", "", "", "", "Sim"]});
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "LCA Emis Safra Pre 12,42% venc12/12/22", "Renda Fixa", "", 68000.0, 71101.35, "", "", "", "", "", "", "", "", "Sim"]});
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "RF.LCA vence 14/3/24", "Renda Fixa", "", 30134.37, 30677.93, "", "", "", "", "", "", "", "", "Sim"]});
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "RF.LCA vence 18/3/24", "Renda Fixa", "", 50187.11, 51133.21, "", "", "", "", "", "", "", "", "Sim"]});
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "RF.LCA vence 21/3/24", "Renda Fixa", "", 30078.39, 30678.6, "", "", "", "", "", "", "", "", "Sim"]});
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "CRA LCI BCO INTERMEDIUM vence mar 25", "Renda Fixa", "", 24344.03, 26527.4, "", "", "", "", "", "", "", "", "Sim"]});
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "RF. Banco ABC Brasil vence 24.7", "Renda Fixa", "", 53071.05, 55947.56, "", "", "", "", "", "", "", "", "Sim"]});
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "PRIO3 - Collar Kin Cupom venc 17.08.2023", "Estruturada", "", 15000.0, 17006.26, "", "", "", "", "", "", "", "", "Sim"]});
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "RRRP3 - Estruturada 6meses", "Estruturada", "", 15000.0, 15029.86, "", "", "", "", "", "", "", "", "Sim"]});
  await sheetsPost({action:'appendLog',sheet:'Investimentos',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "Multimercado", "", 5000.0, 4166.03, "", "", "", "", "", "", "", "", "Sim"]});
  console.log('Ativos criados: 24');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM. MAN Absolute Vertex FIC FIM", "26/06/2022", 20000.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM. MAN Absolute Vertex FIC FIM", "26/07/2022", 19932.21, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM. MAN Absolute Vertex FIC FIM", "25/08/2022", 20419.53, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM. MAN Absolute Vertex FIC FIM", "29/09/2022", 21468.36, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM. MAN Absolute Vertex FIC FIM", "27/10/2022", 21384.98, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM. MAN Absolute Vertex FIC FIM", "02/02/2023", 21589.87, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM. MAN Absolute Vertex FIC FIM", "03/03/2023", 21509.16, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM. MAN Absolute Vertex FIC FIM", "30/03/2023", 21467.79, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM. MAN Absolute Vertex FIC FIM", "01/05/2023", 21627.21, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM. MAN Absolute Vertex FIC FIM", "01/05/2023", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: MM. MAN Absolute Vertex FIC FIM');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM. MAN Ibiuna Hedge FIC FIM", "26/06/2022", 50000.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM. MAN Ibiuna Hedge FIC FIM", "26/07/2022", 49737.69, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM. MAN Ibiuna Hedge FIC FIM", "25/08/2022", 50741.1, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM. MAN Ibiuna Hedge FIC FIM", "29/09/2022", 52322.3, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM. MAN Ibiuna Hedge FIC FIM", "27/10/2022", 52627.92, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM. MAN Ibiuna Hedge FIC FIM", "02/02/2023", 53256.65, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM. MAN Ibiuna Hedge FIC FIM", "03/03/2023", 52997.13, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM. MAN Ibiuna Hedge FIC FIM", "30/03/2023", 52352.35, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM. MAN Ibiuna Hedge FIC FIM", "01/05/2023", 53124.72, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM. MAN Ibiuna Hedge FIC FIM", "01/05/2023", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: MM. MAN Ibiuna Hedge FIC FIM');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 17/05", "04/01/2024", 10531.17, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 17/05", "04/01/2024", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: RF.LCA vence 17/05');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 05/06", "04/01/2024", 34575.46, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 05/06", "04/01/2024", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: RF.LCA vence 05/06');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 03/07", "04/01/2024", 7053.89, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 03/07", "31/01/2024", 7169.38, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 03/07", "13/02/2024", 7169.38, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 03/07", "13/02/2024", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: RF.LCA vence 03/07');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 21/08", "31/01/2024", 18260.7, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 21/08", "13/02/2024", 18400.73, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 21/08", "13/02/2024", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: RF.LCA vence 21/08');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 5/09", "31/01/2024", 75674.93, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 5/09", "13/02/2024", 76253.4, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 5/09", "30/03/2024", 77043.08, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 5/09", "30/03/2024", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: RF.LCA vence 5/09');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 4/12", "31/01/2024", 32283.84, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 4/12", "13/02/2024", 32527.1, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 4/12", "30/03/2024", 32859.12, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 4/12", "30/04/2024", 33135.96, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 4/12", "09/06/2024", 33415.12, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 4/12", "16/06/2024", 33637.18, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 4/12", "16/06/2024", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: RF.LCA vence 4/12');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "LCA Safra pre vence 30/11", "30/04/2024", 15112.71, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "LCA Safra pre vence 30/11", "09/06/2024", 15232.61, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "LCA Safra pre vence 30/11", "09/06/2024", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: LCA Safra pre vence 30/11');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "LCA vence 04/12/2023", "30/04/2024", 50329.8, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "LCA vence 04/12/2023", "09/06/2024", 50724.28, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "LCA vence 04/12/2023", "16/06/2024", 51037.89, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "LCA vence 04/12/2023", "16/06/2024", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: LCA vence 04/12/2023');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "LCA Safra pre vence 18/12", "30/04/2024", 65000.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "LCA Safra pre vence 18/12", "09/06/2024", 65716.26, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "LCA Safra pre vence 18/12", "16/06/2024", 66117.59, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "LCA Safra pre vence 18/12", "16/06/2024", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: LCA Safra pre vence 18/12');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM LCAPR PRE 11.85% v.5/9", "04/08/2024", 29298.58, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM LCAPR PRE 11.85% v.5/9", "30/08/2024", 29559.58, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM LCAPR PRE 11.85% v.5/9", "30/08/2024", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: TCM LCAPR PRE 11.85% v.5/9');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM LCAPR PRE 11.75% v.9/10", "04/08/2024", 9808.36, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM LCAPR PRE 11.75% v.9/10", "30/08/2024", 9908.32, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM LCAPR PRE 11.75% v.9/10", "05/10/2024", 9991.66, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "TCM LCAPR PRE 11.75% v.9/10", "05/10/2024", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: TCM LCAPR PRE 11.75% v.9/10');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF. LCA Emissao Safra Pre", "04/01/2024", 24889.81, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF. LCA Emissao Safra Pre", "31/01/2024", 17662.26, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF. LCA Emissao Safra Pre", "13/02/2024", 52073.68, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF. LCA Emissao Safra Pre", "30/04/2024", 60084.12, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF. LCA Emissao Safra Pre", "30/04/2024", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: RF. LCA Emissao Safra Pre');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF. CDB emissao terceiros IPCA", "04/01/2024", 4501.35, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF. CDB emissao terceiros IPCA", "04/01/2024", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: RF. CDB emissao terceiros IPCA');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "LCA Emis Safra Pre 12,42% venc12/12/22", "26/06/2022", 68000.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "LCA Emis Safra Pre 12,42% venc12/12/22", "26/07/2022", 68986.39, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "LCA Emis Safra Pre 12,42% venc12/12/22", "25/08/2022", 69792.29, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "LCA Emis Safra Pre 12,42% venc12/12/22", "29/09/2022", 70443.78, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "LCA Emis Safra Pre 12,42% venc12/12/22", "27/10/2022", 71101.35, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "LCA Emis Safra Pre 12,42% venc12/12/22", "27/10/2022", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: LCA Emis Safra Pre 12,42% venc12/12');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 14/3/24", "04/01/2024", 30134.37, "31.1k/dez.23"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 14/3/24", "31/01/2024", 30348.37, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 14/3/24", "13/02/2024", 30438.93, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 14/3/24", "13/02/2024", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: RF.LCA vence 14/3/24');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 18/3/24", "04/01/2024", 50187.11, "50.1k/dez.23"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 18/3/24", "31/01/2024", 50544.55, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 18/3/24", "13/02/2024", 50695.81, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 18/3/24", "13/02/2024", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: RF.LCA vence 18/3/24');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 21/3/24", "04/01/2024", 30078.39, "30k/dez.23"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 21/3/24", "31/01/2024", 30392.19, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 21/3/24", "13/02/2024", 30382.67, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF.LCA vence 21/3/24", "13/02/2024", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: RF.LCA vence 21/3/24');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "CRA LCI BCO INTERMEDIUM vence mar 25", "30/04/2024", 24344.03, "24.2k/abr.24"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "CRA LCI BCO INTERMEDIUM vence mar 25", "09/06/2024", 24586.22, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "CRA LCI BCO INTERMEDIUM vence mar 25", "16/06/2024", 24632.86, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "CRA LCI BCO INTERMEDIUM vence mar 25", "04/08/2024", 24961.86, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "CRA LCI BCO INTERMEDIUM vence mar 25", "30/08/2024", 25142.29, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "CRA LCI BCO INTERMEDIUM vence mar 25", "05/10/2024", 25393.98, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "CRA LCI BCO INTERMEDIUM vence mar 25", "10/11/2024", 22418.89, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "CRA LCI BCO INTERMEDIUM vence mar 25", "30/11/2024", 22294.06, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "CRA LCI BCO INTERMEDIUM vence mar 25", "08/12/2024", 25998.32, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "CRA LCI BCO INTERMEDIUM vence mar 25", "11/01/2025", 26089.98, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "CRA LCI BCO INTERMEDIUM vence mar 25", "06/03/2025", 26527.4, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "CRA LCI BCO INTERMEDIUM vence mar 25", "06/03/2025", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: CRA LCI BCO INTERMEDIUM vence mar 2');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF. Banco ABC Brasil vence 24.7", "04/01/2024", 53071.05, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF. Banco ABC Brasil vence 24.7", "31/01/2024", 53556.23, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF. Banco ABC Brasil vence 24.7", "13/02/2024", 53996.69, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF. Banco ABC Brasil vence 24.7", "30/03/2024", 54490.33, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF. Banco ABC Brasil vence 24.7", "30/04/2024", 55013.51, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF. Banco ABC Brasil vence 24.7", "09/06/2024", 55642.9, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RF. Banco ABC Brasil vence 24.7", "09/06/2024", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: RF. Banco ABC Brasil vence 24.7');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "PRIO3 - Collar Kin Cupom venc 17.08.2023", "13/02/2024", 15000.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "PRIO3 - Collar Kin Cupom venc 17.08.2023", "30/03/2024", 15075.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "PRIO3 - Collar Kin Cupom venc 17.08.2023", "30/04/2024", 15150.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "PRIO3 - Collar Kin Cupom venc 17.08.2023", "09/06/2024", 15225.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "PRIO3 - Collar Kin Cupom venc 17.08.2023", "16/06/2024", 15300.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "PRIO3 - Collar Kin Cupom venc 17.08.2023", "04/08/2024", 15375.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "PRIO3 - Collar Kin Cupom venc 17.08.2023", "04/08/2024", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: PRIO3 - Collar Kin Cupom venc 17.08');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RRRP3 - Estruturada 6meses", "05/10/2024", 15000.0, "15k/set.23"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RRRP3 - Estruturada 6meses", "10/11/2024", 15300.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RRRP3 - Estruturada 6meses", "30/11/2024", 15606.0, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RRRP3 - Estruturada 6meses", "08/12/2024", 15918.12, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RRRP3 - Estruturada 6meses", "11/01/2025", 16236.48, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RRRP3 - Estruturada 6meses", "06/03/2025", 16561.21, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "RRRP3 - Estruturada 6meses", "06/03/2025", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: RRRP3 - Estruturada 6meses');
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "26/06/2022", 5000.0, "5k/jun.22"]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "26/07/2022", 4568.38, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "25/08/2022", 5373.68, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "29/09/2022", 3982.57, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "27/10/2022", 4934.57, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "02/02/2023", 5770.78, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "03/03/2023", 5626.1, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "30/03/2023", 5547.89, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "01/05/2023", 5406.13, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "31/05/2023", 5060.76, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "06/07/2023", 5385.57, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "31/07/2023", 5603.17, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "31/08/2023", 5500.9, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "28/09/2023", 5282.51, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "25/10/2023", 5159.79, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "30/11/2023", 4973.53, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "04/01/2024", 4848.14, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "31/01/2024", 4067.21, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "13/02/2024", 3809.33, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "30/03/2024", 3980.16, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "30/04/2024", 4277.27, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "09/06/2024", 5215.8, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "16/06/2024", 4307.21, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "04/08/2024", 4458.28, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "30/08/2024", 4507.9, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "05/10/2024", 4166.03, ""]});
  if(r&&r.ok)sent++; else erros++;
  var r=await sheetsPost({action:'appendLog',sheet:'InvestimentosLog',row:["ALE", "Safra", "MM.SAF Direct Carbono Reais FIM", "05/10/2024", 0, "Encerrado — transferido para Safra CC"]});
  if(r&&r.ok)sent++; else erros++;
  console.log('logs ok: MM.SAF Direct Carbono Reais FIM');
  await sheetsAppend(["01/05/2023", "Resgate MM. MAN Absolute Vertex FIC FIM", "21627,21", "Investimentos", "Investimentos", "MM. MAN Absolute Vertex FIC FIM", "saida", "1", "", "", "saf_MM.MANS"]);
  await sheetsAppend(["01/05/2023", "Resgate MM. MAN Absolute Vertex FIC FIM", "21627,21", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_MM.MANE"]);
  txSent++;
  await sheetsAppend(["01/05/2023", "Resgate MM. MAN Ibiuna Hedge FIC FIM", "53124,72", "Investimentos", "Investimentos", "MM. MAN Ibiuna Hedge FIC FIM", "saida", "1", "", "", "saf_MM.MANS"]);
  await sheetsAppend(["01/05/2023", "Resgate MM. MAN Ibiuna Hedge FIC FIM", "53124,72", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_MM.MANE"]);
  txSent++;
  await sheetsAppend(["04/01/2024", "Resgate RF.LCA vence 17/05", "10531,17", "Investimentos", "Investimentos", "RF.LCA vence 17/05", "saida", "1", "", "", "saf_RF.LCAvS"]);
  await sheetsAppend(["04/01/2024", "Resgate RF.LCA vence 17/05", "10531,17", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_RF.LCAvE"]);
  txSent++;
  await sheetsAppend(["04/01/2024", "Resgate RF.LCA vence 05/06", "34575,46", "Investimentos", "Investimentos", "RF.LCA vence 05/06", "saida", "1", "", "", "saf_RF.LCAvS"]);
  await sheetsAppend(["04/01/2024", "Resgate RF.LCA vence 05/06", "34575,46", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_RF.LCAvE"]);
  txSent++;
  await sheetsAppend(["13/02/2024", "Resgate RF.LCA vence 03/07", "7192,06", "Investimentos", "Investimentos", "RF.LCA vence 03/07", "saida", "1", "", "", "saf_RF.LCAvS"]);
  await sheetsAppend(["13/02/2024", "Resgate RF.LCA vence 03/07", "7192,06", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_RF.LCAvE"]);
  txSent++;
  await sheetsAppend(["13/02/2024", "Resgate RF.LCA vence 21/08", "18525,18", "Investimentos", "Investimentos", "RF.LCA vence 21/08", "saida", "1", "", "", "saf_RF.LCAvS"]);
  await sheetsAppend(["13/02/2024", "Resgate RF.LCA vence 21/08", "18525,18", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_RF.LCAvE"]);
  txSent++;
  await sheetsAppend(["30/03/2024", "Resgate RF.LCA vence 5/09", "77146,68", "Investimentos", "Investimentos", "RF.LCA vence 5/09", "saida", "1", "", "", "saf_RF.LCAvS"]);
  await sheetsAppend(["30/03/2024", "Resgate RF.LCA vence 5/09", "77146,68", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_RF.LCAvE"]);
  txSent++;
  await sheetsAppend(["16/06/2024", "Resgate RF.LCA vence 4/12", "33786,04", "Investimentos", "Investimentos", "RF.LCA vence 4/12", "saida", "1", "", "", "saf_RF.LCAvS"]);
  await sheetsAppend(["16/06/2024", "Resgate RF.LCA vence 4/12", "33786,04", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_RF.LCAvE"]);
  txSent++;
  await sheetsAppend(["09/06/2024", "Resgate LCA Safra pre vence 30/11", "15379,03", "Investimentos", "Investimentos", "LCA Safra pre vence 30/11", "saida", "1", "", "", "saf_LCASafrS"]);
  await sheetsAppend(["09/06/2024", "Resgate LCA Safra pre vence 30/11", "15379,03", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_LCASafrE"]);
  txSent++;
  await sheetsAppend(["16/06/2024", "Resgate LCA vence 04/12/2023", "51248,04", "Investimentos", "Investimentos", "LCA vence 04/12/2023", "saida", "1", "", "", "saf_LCAvencS"]);
  await sheetsAppend(["16/06/2024", "Resgate LCA vence 04/12/2023", "51248,04", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_LCAvencE"]);
  txSent++;
  await sheetsAppend(["16/06/2024", "Resgate LCA Safra pre vence 18/12", "66656,51", "Investimentos", "Investimentos", "LCA Safra pre vence 18/12", "saida", "1", "", "", "saf_LCASafrS"]);
  await sheetsAppend(["16/06/2024", "Resgate LCA Safra pre vence 18/12", "66656,51", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_LCASafrE"]);
  txSent++;
  await sheetsAppend(["30/08/2024", "Resgate TCM LCAPR PRE 11.85% v.5/9", "29639,07", "Investimentos", "Investimentos", "TCM LCAPR PRE 11.85% v.5/9", "saida", "1", "", "", "saf_TCMLCAPS"]);
  await sheetsAppend(["30/08/2024", "Resgate TCM LCAPR PRE 11.85% v.5/9", "29639,07", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_TCMLCAPE"]);
  txSent++;
  await sheetsAppend(["05/10/2024", "Resgate TCM LCAPR PRE 11.75% v.9/10", "10022,55", "Investimentos", "Investimentos", "TCM LCAPR PRE 11.75% v.9/10", "saida", "1", "", "", "saf_TCMLCAPS"]);
  await sheetsAppend(["05/10/2024", "Resgate TCM LCAPR PRE 11.75% v.9/10", "10022,55", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_TCMLCAPE"]);
  txSent++;
  await sheetsAppend(["30/04/2024", "Resgate RF. LCA Emissao Safra Pre", "60084,12", "Investimentos", "Investimentos", "RF. LCA Emissao Safra Pre", "saida", "1", "", "", "saf_RF.LCAS"]);
  await sheetsAppend(["30/04/2024", "Resgate RF. LCA Emissao Safra Pre", "60084,12", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_RF.LCAE"]);
  txSent++;
  await sheetsAppend(["04/01/2024", "Resgate RF. CDB emissao terceiros IPCA", "4501,35", "Investimentos", "Investimentos", "RF. CDB emissao terceiros IPCA", "saida", "1", "", "", "saf_RF.CDBS"]);
  await sheetsAppend(["04/01/2024", "Resgate RF. CDB emissao terceiros IPCA", "4501,35", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_RF.CDBE"]);
  txSent++;
  await sheetsAppend(["27/10/2022", "Resgate LCA Emis Safra Pre 12,42% venc12/12/22", "71101,35", "Investimentos", "Investimentos", "LCA Emis Safra Pre 12,42% venc12/12/22", "saida", "1", "", "", "saf_LCAEmisS"]);
  await sheetsAppend(["27/10/2022", "Resgate LCA Emis Safra Pre 12,42% venc12/12/22", "71101,35", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_LCAEmisE"]);
  txSent++;
  await sheetsAppend(["13/02/2024", "Resgate RF.LCA vence 14/3/24", "30677,93", "Investimentos", "Investimentos", "RF.LCA vence 14/3/24", "saida", "1", "", "", "saf_RF.LCAvS"]);
  await sheetsAppend(["13/02/2024", "Resgate RF.LCA vence 14/3/24", "30677,93", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_RF.LCAvE"]);
  txSent++;
  await sheetsAppend(["13/02/2024", "Resgate RF.LCA vence 18/3/24", "51133,21", "Investimentos", "Investimentos", "RF.LCA vence 18/3/24", "saida", "1", "", "", "saf_RF.LCAvS"]);
  await sheetsAppend(["13/02/2024", "Resgate RF.LCA vence 18/3/24", "51133,21", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_RF.LCAvE"]);
  txSent++;
  await sheetsAppend(["13/02/2024", "Resgate RF.LCA vence 21/3/24", "30678,6", "Investimentos", "Investimentos", "RF.LCA vence 21/3/24", "saida", "1", "", "", "saf_RF.LCAvS"]);
  await sheetsAppend(["13/02/2024", "Resgate RF.LCA vence 21/3/24", "30678,6", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_RF.LCAvE"]);
  txSent++;
  await sheetsAppend(["06/03/2025", "Resgate CRA LCI BCO INTERMEDIUM vence mar 25", "26527,4", "Investimentos", "Investimentos", "CRA LCI BCO INTERMEDIUM vence mar 25", "saida", "1", "", "", "saf_CRALCIS"]);
  await sheetsAppend(["06/03/2025", "Resgate CRA LCI BCO INTERMEDIUM vence mar 25", "26527,4", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_CRALCIE"]);
  txSent++;
  await sheetsAppend(["09/06/2024", "Resgate RF. Banco ABC Brasil vence 24.7", "55947,56", "Investimentos", "Investimentos", "RF. Banco ABC Brasil vence 24.7", "saida", "1", "", "", "saf_RF.BancS"]);
  await sheetsAppend(["09/06/2024", "Resgate RF. Banco ABC Brasil vence 24.7", "55947,56", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_RF.BancE"]);
  txSent++;
  await sheetsAppend(["04/08/2024", "Resgate PRIO3 - Collar Kin Cupom venc 17.08.2023", "17006,26", "Investimentos", "Investimentos", "PRIO3 - Collar Kin Cupom venc 17.08.2023", "saida", "1", "", "", "saf_PRIO3-S"]);
  await sheetsAppend(["04/08/2024", "Resgate PRIO3 - Collar Kin Cupom venc 17.08.2023", "17006,26", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_PRIO3-E"]);
  txSent++;
  await sheetsAppend(["06/03/2025", "Resgate RRRP3 - Estruturada 6meses", "15029,86", "Investimentos", "Investimentos", "RRRP3 - Estruturada 6meses", "saida", "1", "", "", "saf_RRRP3-S"]);
  await sheetsAppend(["06/03/2025", "Resgate RRRP3 - Estruturada 6meses", "15029,86", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_RRRP3-E"]);
  txSent++;
  await sheetsAppend(["05/10/2024", "Resgate MM.SAF Direct Carbono Reais FIM", "4166,03", "Investimentos", "Investimentos", "MM.SAF Direct Carbono Reais FIM", "saida", "1", "", "", "saf_MM.SAFDS"]);
  await sheetsAppend(["05/10/2024", "Resgate MM.SAF Direct Carbono Reais FIM", "4166,03", "Investimentos", "Investimentos", "Safra CC", "entrada", "1", "", "", "saf_MM.SAFDE"]);
  txSent++;
  console.log('Total logs:',sent,'erros:',erros,'tx:',txSent);
  alert('Concluido! '+sent+' logs, '+txSent+' transferencias. Erros: '+erros);
})();